spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_blog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: Dd112211
  redis:
    port: 6379
    host: 127.0.0.1
    password: MyRedisPwd123
  cache:
    type: redis
    redis:
      time-to-live: 24h
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  mvc:
    static-path-pattern: /static/**
mybatis-plus:
  #configuration:
  #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: blog_
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
logging:
  file:
    path: log
  logback:
    rollingpolicy:
      clean-history-on-start: true
      max-file-size: 5MB
server:
  port: 8888
  servlet:
    context-path: /api